spring:
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: wikimedia-streams-processor
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        commit.interval.ms: 1000
        cache.max.bytes.buffering: 10485760
  application:
    name: wikimedia-streams-processor

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.wikimedia.streams: INFO
    org.apache.kafka: WARN
